language: csharp
solution: Compost.NET.sln
install:
    - nuget restore Compost.NET.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
    - ./updateVersion.sh
script:
    - xbuild /p:Configuration=Release Compost.NET.sln
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/tests/Release/Compost.Tests.dll
after_success:
    - ./publishToNuget.sh